### ISSUE TITLE
Setting Notification-Coalescing-ID

### ISSUE THREAD

**Issue by onderweg** [theabraham/growly#9]
I'd like to be able to set the Growl Notification-Coalescing-ID, when sending a notification.

Current situation in growly.js:
```
gntp.add('Notification-Coalescing-ID', undefined);
```

Maybe this can be changed to something like

```
gntp.add('Notification-Coalescing-ID', opts.coalescing || undefined);
```

**Comment by theabraham** [comment]
Ok, this change is published with version 1.3.0. Thanks again.
